version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types: ["minor", "patch"]
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/static/confluence-macro"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/static/jira-panel"
    schedule:
      interval: "weekly"
